### ISSUE TITLE
Running the tests gives a segmentation fault.

### ISSUE THREAD

**Issue by shivamvats** [rizar/actor-critic-public#1]
@rizar I followed the instructions in README to run the tests. However, I am getting seg faults for all the tests I tried. My guess is that code is not getting the correct data. Are there additional steps I need to take to properly set the run time paths?

**Comment by rizar** [comment]
By "tests", do you mean the content of "tests" folder, or do you mean the actual experiments? The former was included in the repository by mistake and should be deleted.

**Comment by shivamvats** [comment]
I am sorry for the confusion. I mean the actual experiments `billion words` and `ted` used in the paper.

**Comment by rizar** [comment]
OK, I see. Can you please provide a bit more information about the exact
commands that you ran?

**Comment by shivamvats** [comment]
1. `source env.sh`.
2. `cd exp/billion_words`
3.  ` $LVSR/bin/run.py train autoencoder3 configs/autoencoder3.yaml`
4. `cd ../ted`
5. `./create_dataset.sh` (I first set the path to MOSES)`
6. `$LVSR/bin/run.py train ted12 config/ted12.yaml`

Error: 

```
Using gpu device 0: GeForce GTX 960M (CNMeM is enabled with initial size: 90.0% of memory, cuDNN not available)    
Segmentation fault
```

**Comment by rizar** [comment]
Hold on, did the step 3 work for you? You should've downloaded the data first. I will add the instruction on how to download the data today.

**Comment by rizar** [comment]
https://github.com/rizar/actor-critic-public/blob/master/exp/billion_words/README.md is now updated

**Comment by shivamvats** [comment]
I did download the data (I put it in `lvsr/datasets` though).

I still get the same error after putting the data in `FUEL_DATA_PATH`. I am surprised to see a seg fault with Python. Are you using C wrappers in your code? From fuel's docs, it seems that it needs data as  a `.hdf5` file. Does it need to be converted to fuel's format?

Also, in the configs for `ted` the data filename is set as `TED/de-en/ted.h5` (I would expect it to be `ted.h5`).

**Comment by rizar** [comment]
No, their is no C code in our implementation. But libhdf5 could trigger
one. But let's focus on one experiment. Do you have a segfault when you are
trying to run on TED or on billion_words?

**Comment by shivamvats** [comment]
Both.

**Comment by rizar** [comment]
OK, let's focus on billion words then. In order to help you, I would need
to know at which line of lvsr/main.py the segmentation fault happens.

**Comment by shivamvats** [comment]
I figured out the issue. Importing `fst` is leading to a seg fault. I tried reinstalling pyfst and openfst but it doesn't work. The code should work without `fst`, right?

**Comment by rizar** [comment]
Yes, this an obsolete import. Feel free to remove it. I will remove it
later as well. Thanks for the heads-up!

**Comment by shivamvats** [comment]
Thanks a lot for your prompt help! :)
Would it be possible for you to give me a rough estimate of the training time? I am using a GTX 960, with 4GB memory.

**Comment by rizar** [comment]
I am afraid this amount of memory might not be sufficient. On a K80 the
pretraining (first actor, then critic) takes about 36 hours, and then you
can run the main stage for as long as you want...

**Comment by Fatman003** [comment]
Hi @rizar @shivamvats I have been following the same procedure listed in this issue but I do however get a valueError when running the billion_word training experiment ($LVSR/bin/run.py train autoencoder3 configs/autoencoder3.yaml) which says "if target_source != 'text': raise valueError." (from ..lvsr/datasets/text.py) I would like to know the python version this experiment was run on and any other tips I can use to debug my error?
