### ISSUE TITLE
Question about the convEncoder

### ISSUE THREAD

**Issue by wenhuchen** [rizar/actor-critic-public#2]
In the file lvsr/bricks/\_\_init\_\_.py, the apply function of class ConvEncoder looks a bit weird. It seems to add the kernel function and do a summation over a window to get the output, it's quite different from the normal spatialconvolution function. Do I understand correctly?

**Comment by rizar** [comment]
`ConvEncoder` was an attempt to reproduce the results by [Ranzato et. al](https://arxiv.org/pdf/1511.06732.pdf). It is described in subsection 6.2 of the manuscript. It is indeed a very restricted architecture.
